config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  :controllers => {:registrations => "users/registrations"}
  root 'posts#index'

  resources :users, only: [:show, :index, :update]
  resources :friend_requests, only: [:create, :destroy]
  resources :friends, only: [:create, :destroy]
  resources :users do
    resources :posts
  end
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = self.email.downcase }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :sent_friend_requests, foreign_key: "requestor_id", class_name: "FriendRequest"
  has_many :received_friend_requests, foreign_key: "requestee_id", class_name: "FriendRequest"
  has_many :friends
  has_many :likes
  has_one_attached :avatar

  validates :name, presence: true, length: { maximum: 30 },
    format: { with: /\A[a-zA-Z]+\z/,
              message: "Names can only contain letters" }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, 
              message: "Emails can only contain certain characters" }
  validates :password, presence: true, length: { maximum: 30 }
  validates :password_confirmation, presence: true, length: { maximum: 30 }
  #add validation for about_me

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
     super
     if @user.valid?
      UserMailer.with(user: @user).welcome_email.deliver_later
     else
      flash[:error] = "An error occurred."
     end
     
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
        @list_of_received_friend_requests = current_user.received_friend_requests

        @list_of_friends = current_user.friends

        @special_list = list_of_users_not_friends_with_and_has_not_sent_a_request

        @friend_request = FriendRequest.new
    end

    def show
        @user = User.find_by(:id => params[:id])
        @list_of_posts = @user.posts
        @friend_request = FriendRequest.new
    end

    def update
        @user = User.find_by(:id => params[:id])
        @user.avatar.attach(params[:avatar])
        @user.update_attributes(params[:about_me])
    end

    def already_a_friend(user_id)
        if current_user.friends.find_by(:friend_id => user_id) != nil
            return true
        else
            return false
        end
    end

    def already_sent_a_request(user_id)
        if current_user.sent_friend_requests.find_by(:requestee_id => user_id) != nil
            return true
        else
            return false
        end
    end

    def already_received_a_request(user_id)
        if current_user.received_friend_requests.find_by(:requestor_id => user_id) != nil
            return true
        else
            return false
        end
    end

    def list_of_users_not_friends_with_and_has_not_sent_a_request
        list_of_friends_ids = current_user.friends.map { |friend| friend.friend_id}
        list_of_sent_friend_requests_ids = current_user.sent_friend_requests.map { |request| request.requestee_id}
        list_of_received_friend_requests_ids = current_user.received_friend_requests.map { |request| request.requestor_id}

        combined_list = list_of_friends_ids.concat(list_of_sent_friend_requests_ids)
        combined_list = combined_list.concat(list_of_received_friend_requests_ids)

        #Add current user's id to the list, so they will not show up in the user's index
        combined_list.push(current_user.id)

        return User.where.not(id: combined_list)
    end

    helper_method :already_a_friend, :already_sent_a_request, :already_received_a_request, :list_of_users_not_friends_with_and_has_not_sent_a_request
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="userIndex">
    <h1 class="friendRequestsTitle"> Received Friend Requests </h1>

    <div class="friendRequests">
        <% if !@list_of_received_friend_requests.empty? %>
            <% @list_of_received_friend_requests.each do |request| %>

                <div class="user">
                    <% if User.find_by(:id => request.requestor_id).avatar.attached? %>
                            <%= image_tag(User.find_by(:id => request.requestor_id).avatar, :class => "profilePic") %>
                        <% else %>
                            <%= image_tag("default_profile.jpg", :class => "profilePic") %>
                    <% end %>

                    <div>
                        <b><%= link_to "#{User.find_by(:id => request.requestor_id).name}", user_path(User.find_by(:id => request.requestor_id)), :class => 'name' %></b>
                        <br>
                        <%= link_to "Accept", friends_path(:friend_id => request.requestor_id), method: :post, :class => 'acceptRequest' %>
                        <%= link_to "Decline", friend_request_path(:id => request.id, :requestor_id => request.requestor_id), method: :delete, :class => 'declineRequest' %>
                        <br>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>

    <h1 class="friendsTitle"> Friends </h1>

    <div class="friends">
        <% if !@list_of_friends.empty? %>
            <% @list_of_friends.each do |friend| %>

                <div class="user">
                    <% if User.find_by(:id => friend.friend_id).avatar.attached? %>
                            <%= image_tag(User.find_by(:id => friend.friend_id).avatar, :class => "profilePic") %>
                        <% else %>
                            <%= image_tag("default_profile.jpg", :class => "profilePic") %>
                    <% end %>


                    <div>
                        <%= link_to "#{User.find_by(:id => friend.friend_id).name}", user_path(User.find_by(:id => friend.friend_id).id), :class => 'name' %>
                        <br>
                        <%= link_to "Delete friend", friend_path(:id => friend.id, :friend_id => friend.friend_id), method: :delete, :class => 'deleteFriend' %>
                        <br>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>

    <h1 class="otherUsersTitle"> Other Users </h1>

    <div class="otherUsers">
        <% if !@special_list.empty? %>
            <% @special_list.each do |x| %>
                <div class="user">
                    <% if x.avatar.attached? %>
                        <%= image_tag(x.avatar, :class => "profilePic") %>
                    <% else %>
                        <%= image_tag("default_profile.jpg", :class => "profilePic") %>
                    <% end %>

                    <div>
                        <%= link_to "#{x.name}", user_path(x.id), :class => 'name' %>

                        <%= form_with model: @friend_request, url: friend_requests_path, local: true do |f| %>

                            <%= f.hidden_field :requestee_id, value: x.id %>

                            <%= f.submit "Send friend request.", :class => 'friendRequestBtn' %>
                        <% end %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="userShow">
    <h1 class="pageTitle"> <%= @user.name %> </h1>

    <% if current_user.id == @user.id %>
        <p>
            <%= link_to "Edit Account", edit_user_registration_path %>
        </p>
    <% end %>
    <br>

    <% if @user.avatar.attached? %>
        <%= image_tag(@user.avatar, :class => "profilePic") %>
    <% else %>
        <%= image_tag("default_profile.jpg", :class => "profilePic") %>
    <% end %>

    <div class="about_me">
        <h2 class="about_meTitle"> About Me </h2>

        <p class="content">
            <%= @user.about_me %>
        </p>
    </div>

    <% if current_user.id != @user.id && !already_a_friend(@user.id) && !already_sent_a_request(@user.id) && !already_received_a_request(@user.id) %>
        <%= form_with model: @friend_request, url: friend_requests_path, local: true do |f| %>

            <%= f.hidden_field :requestee_id, value: @user.id %>

            <%= f.submit "Send friend request.", :class => 'friendRequestBtn' %>
        <% end %>
    <% end %>

    <hr>

    <section class="posts">
        <h2>Posts</h2>

        <% @list_of_posts.each do |post| %>
            <article class="post">
                <%= link_to "#{post.title}", user_post_path(post.user.id, post.id), :class => 'title' %>
                <br>
                <% if post.picture.attached? %>
                    <%= image_tag(post.picture, :class => "postPic") %>
                <% end %>
                <br>
                <p class="content"><%= post.content %></p>
                <hr>
            </article>
        <% end %>
    </section>
</div>