config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  :controllers => {:registrations => "users/registrations"}
  root 'posts#index'

  resources :users, only: [:show, :index, :update]
  resources :friend_requests, only: [:create, :destroy]
  resources :friends, only: [:create, :destroy]
  resources :users do
    resources :posts
  end
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes
    has_one_attached :picture

    accepts_nested_attributes_for :comments, allow_destroy: true

    validates :title, presence: true, length: { maximum: 255 }
    validates :content, presence: true, length: { maximum: 10000 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!

    def index
        @list_of_posts = list_of_posts_from_me_and_my_friends.reverse
    end

    def new
        @post = Post.new
    end

    def create
        @post = current_user.posts.build(post_params)

        if @post.save
            flash[:success] = "Post created!"
            redirect_to user_post_url(:user_id => current_user.id, :id => @post.id)
        else
            flash[:error] = "An error occurred."
            redirect_to new_user_post_url(:user_id => current_user.id)
        end 
    end

    def show
        @post = Post.find_by(:id => params[:id])
        @list_of_comments = @post.comments
        @comment = Comment.new
    end

    def destroy
        #post can only be destroyed by author
        Post.find_by(:id => params[:id]).destroy
        flash[:success] = "Post destroyed."
        redirect_to root_url
    end

    def like_exists(post_id)
        if Like.find_by(:user_id => current_user.id, :post_id => post_id)
            return true
        else
            return false
        end
    end

    def list_of_posts_from_me_and_my_friends
        list_of_friends_ids = current_user.friends.map { |friend| friend.friend_id}

        combined_list = list_of_friends_ids.push(current_user.id)

        return Post.where(user_id: combined_list)
    end

    helper_method :like_exists, :list_of_posts_from_me_and_my_friends
    
    private

        def post_params
            params.require(:post).permit(:title, :content, :picture)
        end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="postIndex"> 
    <h1 class="pageTitle"> Everyone's Posts </h1>
    <ol> <% @list_of_posts.each do |post| %>
        <li> 
            <i><span class="name"> <%= post.user.name %> </span></i>
            <br>
            <%= link_to "#{post.title}", user_post_path(post.user.id, post.id), :class => 'link' %>
            <br>
            <% if post.picture.attached? %>
                <%= image_tag(post.picture, :class => "postPic") %>
            <% end %>
            <br>
            <p class="content"> <%= post.content %> </p>
            <hr>
        </li>
    <% end %> </ol> 
    
</div>

app/views/posts/new.html.erb
<div class="postNew">
    <h1 class="pageTitle"> Create a New Post </h1>
    <%= form_with model: @post, url:  user_posts_path, local: true do |f| %>
        <div class="postTitle">
            <%= f.label :title, "Title" %>
            <br>
            <%= f.text_field :title %>
            <br>
        </div>

        <div class="postContent">
            <%= f.label :content, "Content" %>
            <br>
            <%= f.text_area :content %>
            <br>
            <%= f.file_field :picture, :class => 'browseBtn' %>
        </div>

        <%= f.submit "Post", :class => 'submitBtn' %>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="postShow">
    <h1 class="title"> <%= @post.title %> </h1>
    <span class="name"><i> Author: <%= @post.user.name %> </i></span>
    <br>
    <p class="content"> <%= @post.content %> </p>

    <% if @post.picture.attached? %>
        <%= image_tag(@post.picture, :class => "postPic") %>
    <% end %>

    <br>

    <% if current_user.id != @post.user_id %>
        <% if like_exists(@post.id) %>
            <%= link_to "Unlike", like_path(:post_id => @post.id), method: :delete, :class => 'unlike' %>
        <% else %>
            <%= link_to "Like", likes_path(:post_id => @post.id), method: :post, :class => 'like' %>
        <% end %>
    <% else %>
        <%= link_to "Delete Post", user_post_path(@post), method: :delete, data: {confirm: "Are you sure?" }, :class => 'deletePost' %>
    <% end %>

    <hr>
    <h2 class="likeTitle"> Likes </h2>
    <ul class="likes"> <% @post.likes.each do |like| %> 
        <li class="name"> <%= like.user.name %> </li>
    <% end %> </ul>
    <hr>

    <h2 class="commentTitle"> Comments </h2>
    <% if !@list_of_comments.empty? %>
        <ol class="comments"> <% @list_of_comments.each do |comment| %>
            <li> 
                <span><b><i> <%= comment.user.name %> said:</i></b></span>

                <div class="comment">
                    <%= comment.content %>
                </div>

                <% if ((comment.user_id == current_user.id) || (@post.user.id == current_user.id)) %>
                    <%= link_to "Delete Comment", comment_path(:id => comment.id, :post_id => @post.id), method: :delete, data: {confirm: "Are you sure?" }, :class => 'deleteComment' %>
                <% end %>
            </li> <br>
        <% end %> </ol> 
    <% end %>

    <br>
    <%= form_with model: @comment, url: comments_path, local: true do |f| %>
        <%= f.text_area :content, rows:15, cols:80, :class => 'commentContent' %>

        <%= f.hidden_field :post_id, value: @post.id %>

        <br>

        <%= f.submit "Comment", :class => 'commentBtn' %>
    <% end %>
</div>