config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  :controllers => {:registrations => "users/registrations"}
  root 'posts#index'

  resources :users, only: [:show, :index, :update]
  resources :friend_requests, only: [:create, :destroy]
  resources :friends, only: [:create, :destroy]
  resources :users do
    resources :posts
  end
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>FacebookClone</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'reset', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>

      <nav class="navbar">
          <% if user_signed_in? %>
            <li class="sign"> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </li>
            <li> <%= link_to "Home", root_path %> </li>
            <li> <%= link_to "Profile", user_path(current_user.id) %> </li>
            <li> <%= link_to "Users", users_path %> </li>
            <li> <%= link_to "New Post", new_user_post_path(current_user.id) %> </li>
          <% else %>
            <li class="sign"> <%= link_to "Sign in", new_user_session_path %> </li>
            <li class="sign"> <%= link_to "Sign up", new_user_registration_path %> </li>
          <% end %>
      </nav>

      <% flash.each do |type, msg| %>
        <div class="errors">
          <%= msg %>
        </div>
      <% end %>
    </header>
    
    <main>
      <%= yield %>
    </main>
  </body>
</html>